services:
  ral2025_reprod:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    restart: "no"
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./:/home/dev/work
      - ${DATA_DIR:PATHTODATASET}:/home/dev/work/data/
    environment:
      - DISPLAY=${DISPLAY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, compute, utility, graphics]
